version: '3.8'
services:
  hotel-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_URLS=http://*:8080
      - REDIS_CONNECTION=redis:6379
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"